/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalUsers' : bigint,
  'totalDonations' : bigint,
  'totalSmiles' : bigint,
}
export interface Badge {
  'id' : BadgeId,
  'icon' : string,
  'name' : string,
  'description' : string,
  'earnedAt' : bigint,
}
export type BadgeId = { 'TOKENS_100' : null } |
  { 'TOKENS_500' : null } |
  { 'TOKENS_1000' : null } |
  { 'STREAK_30' : null } |
  { 'STREAK_3' : null } |
  { 'STREAK_7' : null };
export interface ChatMessage { 'content' : string, 'role' : string }
export interface Donation {
  'id' : string,
  'paymentMethod' : string,
  'createdAt' : bigint,
  'donorName' : string,
  'message' : [] | [string],
  'donorPrincipal' : string,
  'amount' : string,
}
export interface LeaderboardEntry {
  'userName' : string,
  'userId' : string,
  'createdAt' : bigint,
  'rank' : bigint,
  'likes' : bigint,
  'userCountry' : string,
  'imageBlobId' : string,
  'smileId' : string,
}
export interface LikeNotification {
  'id' : string,
  'likerName' : string,
  'read' : boolean,
  'likerId' : Principal,
  'timestamp' : bigint,
  'smileOwnerId' : Principal,
  'smileId' : string,
}
export interface RegisterInput {
  'country' : string,
  'name' : string,
  'email' : string,
}
export type Result = { 'ok' : UserProfile } |
  { 'err' : string };
export type Result_1 = { 'ok' : string } |
  { 'err' : string };
export type Result_2 = { 'ok' : Donation } |
  { 'err' : string };
export type Result_3 = { 'ok' : Smile } |
  { 'err' : string };
export type Result_4 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_5 = {
    'ok' : { 'shares' : bigint, 'views' : bigint, 'likes' : bigint }
  } |
  { 'err' : string };
export type Result_6 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_7 = { 'ok' : null } |
  { 'err' : string };
export interface Smile {
  'id' : string,
  'profilePicUrl' : [] | [string],
  'userName' : string,
  'shares' : bigint,
  'userState' : [] | [string],
  'views' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'likedBy' : Array<Principal>,
  'likes' : bigint,
  'inviteCode' : [] | [string],
  'userCountry' : string,
  'userRegion' : [] | [string],
  'imageBlobId' : string,
}
export interface SmileInput {
  'userState' : [] | [string],
  'inviteCode' : [] | [string],
  'userRegion' : [] | [string],
  'imageBlobId' : string,
}
export interface TopDonor {
  'donorName' : string,
  'rank' : bigint,
  'totalAmount' : string,
  'donorPrincipal' : string,
  'donationCount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateProfileInput {
  'bio' : [] | [string],
  'name' : [] | [string],
  'email' : [] | [string],
  'isPublic' : [] | [boolean],
  'phone' : [] | [string],
  'location' : [] | [string],
}
export interface UserProfile {
  'id' : Principal,
  'bio' : [] | [string],
  'profilePicUrl' : [] | [string],
  'lastLoginTime' : bigint,
  'referralCode' : string,
  'country' : string,
  'name' : string,
  'badges' : Array<Badge>,
  'joinedAt' : bigint,
  'lastPostDate' : bigint,
  'referralCount' : bigint,
  'deactivatedAt' : [] | [bigint],
  'email' : string,
  'referredBy' : [] | [string],
  'tokens' : bigint,
  'unlockedStickers' : Array<string>,
  'isPublic' : boolean,
  'phone' : [] | [string],
  'totalSmiles' : bigint,
  'location' : [] | [string],
  'currentStreak' : bigint,
}
export interface UserSummary {
  'id' : Principal,
  'country' : string,
  'name' : string,
  'totalSmiles' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'bulkDeleteSmiles' : ActorMethod<[Array<string>], Result_4>,
  'buySticker' : ActorMethod<[string, bigint], Result>,
  'chatWithPookie' : ActorMethod<[string, Array<ChatMessage>], Result_1>,
  'deactivateAccount' : ActorMethod<[], Result_1>,
  'deleteAccount' : ActorMethod<[], Result_1>,
  'deleteSmile' : ActorMethod<[string], Result_7>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllUsers' : ActorMethod<[], Array<UserSummary>>,
  'getCookieConsent' : ActorMethod<[], boolean>,
  'getDonations' : ActorMethod<[], Array<Donation>>,
  'getLastLoginTime' : ActorMethod<[], Result_6>,
  'getMonthlyLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMySmiles' : ActorMethod<[], Array<Smile>>,
  'getNotifications' : ActorMethod<[], Array<LikeNotification>>,
  'getReferralCode' : ActorMethod<[], Result_1>,
  'getSmileAnalytics' : ActorMethod<[string], Result_5>,
  'getSmileByInvite' : ActorMethod<[string], Result_3>,
  'getSmiles' : ActorMethod<[], Array<Smile>>,
  'getTopDonors' : ActorMethod<[], Array<TopDonor>>,
  'getTrendingSmiles' : ActorMethod<[], Array<Smile>>,
  'getWeeklyLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'likeSmile' : ActorMethod<[string], Result_4>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'postSmile' : ActorMethod<[SmileInput], Result_3>,
  'reactivateAccount' : ActorMethod<[], Result_1>,
  'recordDonation' : ActorMethod<
    [string, string, string, [] | [string]],
    Result_2
  >,
  'recordReferral' : ActorMethod<[string], Result_1>,
  'recordSmileShare' : ActorMethod<[string], undefined>,
  'recordSmileView' : ActorMethod<[string], undefined>,
  'registerUser' : ActorMethod<[RegisterInput], Result>,
  'setCookieConsent' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateLastLoginTime' : ActorMethod<[], undefined>,
  'updateProfile' : ActorMethod<[UpdateProfileInput], Result>,
  'updateProfilePicture' : ActorMethod<[string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];