/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result_4 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const BadgeId = IDL.Variant({
  'TOKENS_100' : IDL.Null,
  'TOKENS_500' : IDL.Null,
  'TOKENS_1000' : IDL.Null,
  'STREAK_30' : IDL.Null,
  'STREAK_3' : IDL.Null,
  'STREAK_7' : IDL.Null,
});
export const Badge = IDL.Record({
  'id' : BadgeId,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'earnedAt' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Opt(IDL.Text),
  'profilePicUrl' : IDL.Opt(IDL.Text),
  'lastLoginTime' : IDL.Int,
  'referralCode' : IDL.Text,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'badges' : IDL.Vec(Badge),
  'joinedAt' : IDL.Int,
  'lastPostDate' : IDL.Nat,
  'referralCount' : IDL.Int,
  'deactivatedAt' : IDL.Opt(IDL.Int),
  'email' : IDL.Text,
  'referredBy' : IDL.Opt(IDL.Text),
  'tokens' : IDL.Nat,
  'unlockedStickers' : IDL.Vec(IDL.Text),
  'isPublic' : IDL.Bool,
  'phone' : IDL.Opt(IDL.Text),
  'totalSmiles' : IDL.Nat,
  'location' : IDL.Opt(IDL.Text),
  'currentStreak' : IDL.Nat,
});
export const Result = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Result_7 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const AdminStats = IDL.Record({
  'totalUsers' : IDL.Nat,
  'totalDonations' : IDL.Nat,
  'totalSmiles' : IDL.Nat,
});
export const UserSummary = IDL.Record({
  'id' : IDL.Principal,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'totalSmiles' : IDL.Nat,
});
export const Donation = IDL.Record({
  'id' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'createdAt' : IDL.Int,
  'donorName' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'donorPrincipal' : IDL.Text,
  'amount' : IDL.Text,
});
export const Result_6 = IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text });
export const LeaderboardEntry = IDL.Record({
  'userName' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'rank' : IDL.Nat,
  'likes' : IDL.Nat,
  'userCountry' : IDL.Text,
  'imageBlobId' : IDL.Text,
  'smileId' : IDL.Text,
});
export const Smile = IDL.Record({
  'id' : IDL.Text,
  'profilePicUrl' : IDL.Opt(IDL.Text),
  'userName' : IDL.Text,
  'shares' : IDL.Nat,
  'userState' : IDL.Opt(IDL.Text),
  'views' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'likedBy' : IDL.Vec(IDL.Principal),
  'likes' : IDL.Nat,
  'inviteCode' : IDL.Opt(IDL.Text),
  'userCountry' : IDL.Text,
  'userRegion' : IDL.Opt(IDL.Text),
  'imageBlobId' : IDL.Text,
});
export const LikeNotification = IDL.Record({
  'id' : IDL.Text,
  'likerName' : IDL.Text,
  'read' : IDL.Bool,
  'likerId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'smileOwnerId' : IDL.Principal,
  'smileId' : IDL.Text,
});
export const Result_5 = IDL.Variant({
  'ok' : IDL.Record({
    'shares' : IDL.Nat,
    'views' : IDL.Nat,
    'likes' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const Result_3 = IDL.Variant({ 'ok' : Smile, 'err' : IDL.Text });
export const TopDonor = IDL.Record({
  'donorName' : IDL.Text,
  'rank' : IDL.Nat,
  'totalAmount' : IDL.Text,
  'donorPrincipal' : IDL.Text,
  'donationCount' : IDL.Nat,
});
export const SmileInput = IDL.Record({
  'userState' : IDL.Opt(IDL.Text),
  'inviteCode' : IDL.Opt(IDL.Text),
  'userRegion' : IDL.Opt(IDL.Text),
  'imageBlobId' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : Donation, 'err' : IDL.Text });
export const RegisterInput = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateProfileInput = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'isPublic' : IDL.Opt(IDL.Bool),
  'phone' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'bulkDeleteSmiles' : IDL.Func([IDL.Vec(IDL.Text)], [Result_4], []),
  'buySticker' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
  'chatWithPookie' : IDL.Func([IDL.Text, IDL.Vec(ChatMessage)], [Result_1], []),
  'deactivateAccount' : IDL.Func([], [Result_1], []),
  'deleteAccount' : IDL.Func([], [Result_1], []),
  'deleteSmile' : IDL.Func([IDL.Text], [Result_7], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'getCookieConsent' : IDL.Func([], [IDL.Bool], ['query']),
  'getDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getLastLoginTime' : IDL.Func([], [Result_6], ['query']),
  'getMonthlyLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMySmiles' : IDL.Func([], [IDL.Vec(Smile)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(LikeNotification)], ['query']),
  'getReferralCode' : IDL.Func([], [Result_1], ['query']),
  'getSmileAnalytics' : IDL.Func([IDL.Text], [Result_5], ['query']),
  'getSmileByInvite' : IDL.Func([IDL.Text], [Result_3], ['query']),
  'getSmiles' : IDL.Func([], [IDL.Vec(Smile)], ['query']),
  'getTopDonors' : IDL.Func([], [IDL.Vec(TopDonor)], ['query']),
  'getTrendingSmiles' : IDL.Func([], [IDL.Vec(Smile)], ['query']),
  'getWeeklyLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'likeSmile' : IDL.Func([IDL.Text], [Result_4], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'postSmile' : IDL.Func([SmileInput], [Result_3], []),
  'reactivateAccount' : IDL.Func([], [Result_1], []),
  'recordDonation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result_2],
      [],
    ),
  'recordReferral' : IDL.Func([IDL.Text], [Result_1], []),
  'recordSmileShare' : IDL.Func([IDL.Text], [], []),
  'recordSmileView' : IDL.Func([IDL.Text], [], []),
  'registerUser' : IDL.Func([RegisterInput], [Result], []),
  'setCookieConsent' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateLastLoginTime' : IDL.Func([], [], []),
  'updateProfile' : IDL.Func([UpdateProfileInput], [Result], []),
  'updateProfilePicture' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result_4 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const BadgeId = IDL.Variant({
    'TOKENS_100' : IDL.Null,
    'TOKENS_500' : IDL.Null,
    'TOKENS_1000' : IDL.Null,
    'STREAK_30' : IDL.Null,
    'STREAK_3' : IDL.Null,
    'STREAK_7' : IDL.Null,
  });
  const Badge = IDL.Record({
    'id' : BadgeId,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'earnedAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Opt(IDL.Text),
    'profilePicUrl' : IDL.Opt(IDL.Text),
    'lastLoginTime' : IDL.Int,
    'referralCode' : IDL.Text,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'badges' : IDL.Vec(Badge),
    'joinedAt' : IDL.Int,
    'lastPostDate' : IDL.Nat,
    'referralCount' : IDL.Int,
    'deactivatedAt' : IDL.Opt(IDL.Int),
    'email' : IDL.Text,
    'referredBy' : IDL.Opt(IDL.Text),
    'tokens' : IDL.Nat,
    'unlockedStickers' : IDL.Vec(IDL.Text),
    'isPublic' : IDL.Bool,
    'phone' : IDL.Opt(IDL.Text),
    'totalSmiles' : IDL.Nat,
    'location' : IDL.Opt(IDL.Text),
    'currentStreak' : IDL.Nat,
  });
  const Result = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const ChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const AdminStats = IDL.Record({
    'totalUsers' : IDL.Nat,
    'totalDonations' : IDL.Nat,
    'totalSmiles' : IDL.Nat,
  });
  const UserSummary = IDL.Record({
    'id' : IDL.Principal,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'totalSmiles' : IDL.Nat,
  });
  const Donation = IDL.Record({
    'id' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'createdAt' : IDL.Int,
    'donorName' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'donorPrincipal' : IDL.Text,
    'amount' : IDL.Text,
  });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text });
  const LeaderboardEntry = IDL.Record({
    'userName' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'rank' : IDL.Nat,
    'likes' : IDL.Nat,
    'userCountry' : IDL.Text,
    'imageBlobId' : IDL.Text,
    'smileId' : IDL.Text,
  });
  const Smile = IDL.Record({
    'id' : IDL.Text,
    'profilePicUrl' : IDL.Opt(IDL.Text),
    'userName' : IDL.Text,
    'shares' : IDL.Nat,
    'userState' : IDL.Opt(IDL.Text),
    'views' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'likedBy' : IDL.Vec(IDL.Principal),
    'likes' : IDL.Nat,
    'inviteCode' : IDL.Opt(IDL.Text),
    'userCountry' : IDL.Text,
    'userRegion' : IDL.Opt(IDL.Text),
    'imageBlobId' : IDL.Text,
  });
  const LikeNotification = IDL.Record({
    'id' : IDL.Text,
    'likerName' : IDL.Text,
    'read' : IDL.Bool,
    'likerId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'smileOwnerId' : IDL.Principal,
    'smileId' : IDL.Text,
  });
  const Result_5 = IDL.Variant({
    'ok' : IDL.Record({
      'shares' : IDL.Nat,
      'views' : IDL.Nat,
      'likes' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : Smile, 'err' : IDL.Text });
  const TopDonor = IDL.Record({
    'donorName' : IDL.Text,
    'rank' : IDL.Nat,
    'totalAmount' : IDL.Text,
    'donorPrincipal' : IDL.Text,
    'donationCount' : IDL.Nat,
  });
  const SmileInput = IDL.Record({
    'userState' : IDL.Opt(IDL.Text),
    'inviteCode' : IDL.Opt(IDL.Text),
    'userRegion' : IDL.Opt(IDL.Text),
    'imageBlobId' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : Donation, 'err' : IDL.Text });
  const RegisterInput = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateProfileInput = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'isPublic' : IDL.Opt(IDL.Bool),
    'phone' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'bulkDeleteSmiles' : IDL.Func([IDL.Vec(IDL.Text)], [Result_4], []),
    'buySticker' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
    'chatWithPookie' : IDL.Func(
        [IDL.Text, IDL.Vec(ChatMessage)],
        [Result_1],
        [],
      ),
    'deactivateAccount' : IDL.Func([], [Result_1], []),
    'deleteAccount' : IDL.Func([], [Result_1], []),
    'deleteSmile' : IDL.Func([IDL.Text], [Result_7], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
    'getCookieConsent' : IDL.Func([], [IDL.Bool], ['query']),
    'getDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getLastLoginTime' : IDL.Func([], [Result_6], ['query']),
    'getMonthlyLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMySmiles' : IDL.Func([], [IDL.Vec(Smile)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(LikeNotification)], ['query']),
    'getReferralCode' : IDL.Func([], [Result_1], ['query']),
    'getSmileAnalytics' : IDL.Func([IDL.Text], [Result_5], ['query']),
    'getSmileByInvite' : IDL.Func([IDL.Text], [Result_3], ['query']),
    'getSmiles' : IDL.Func([], [IDL.Vec(Smile)], ['query']),
    'getTopDonors' : IDL.Func([], [IDL.Vec(TopDonor)], ['query']),
    'getTrendingSmiles' : IDL.Func([], [IDL.Vec(Smile)], ['query']),
    'getWeeklyLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'likeSmile' : IDL.Func([IDL.Text], [Result_4], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'postSmile' : IDL.Func([SmileInput], [Result_3], []),
    'reactivateAccount' : IDL.Func([], [Result_1], []),
    'recordDonation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_2],
        [],
      ),
    'recordReferral' : IDL.Func([IDL.Text], [Result_1], []),
    'recordSmileShare' : IDL.Func([IDL.Text], [], []),
    'recordSmileView' : IDL.Func([IDL.Text], [], []),
    'registerUser' : IDL.Func([RegisterInput], [Result], []),
    'setCookieConsent' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateLastLoginTime' : IDL.Func([], [], []),
    'updateProfile' : IDL.Func([UpdateProfileInput], [Result], []),
    'updateProfilePicture' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };