/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    userName: string;
    userId: string;
    createdAt: bigint;
    rank: bigint;
    likes: bigint;
    userCountry: string;
    imageBlobId: string;
    smileId: string;
}
export type Result_2 = {
    __kind__: "ok";
    ok: Donation;
} | {
    __kind__: "err";
    err: string;
};
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SmileInput {
    userState?: string;
    inviteCode?: string;
    userRegion?: string;
    imageBlobId: string;
}
export type Result_6 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface TopDonor {
    donorName: string;
    rank: bigint;
    totalAmount: string;
    donorPrincipal: string;
    donationCount: bigint;
}
export type Result_5 = {
    __kind__: "ok";
    ok: {
        shares: bigint;
        views: bigint;
        likes: bigint;
    };
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Result_4 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface Badge {
    id: BadgeId;
    icon: string;
    name: string;
    description: string;
    earnedAt: bigint;
}
export interface Donation {
    id: string;
    paymentMethod: string;
    createdAt: bigint;
    donorName: string;
    message?: string;
    donorPrincipal: string;
    amount: string;
}
export type Result = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export interface UpdateProfileInput {
    bio?: string;
    name?: string;
    email?: string;
    isPublic?: boolean;
    phone?: string;
    location?: string;
}
export type Result_3 = {
    __kind__: "ok";
    ok: Smile;
} | {
    __kind__: "err";
    err: string;
};
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface UserSummary {
    id: Principal;
    country: string;
    name: string;
    totalSmiles: bigint;
}
export interface RegisterInput {
    country: string;
    name: string;
    email: string;
}
export type Result_7 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface Smile {
    id: string;
    profilePicUrl?: string;
    userName: string;
    shares: bigint;
    userState?: string;
    views: bigint;
    userId: Principal;
    createdAt: bigint;
    likedBy: Array<Principal>;
    likes: bigint;
    inviteCode?: string;
    userCountry: string;
    userRegion?: string;
    imageBlobId: string;
}
export interface LikeNotification {
    id: string;
    likerName: string;
    read: boolean;
    likerId: Principal;
    timestamp: bigint;
    smileOwnerId: Principal;
    smileId: string;
}
export interface ChatMessage {
    content: string;
    role: string;
}
export interface AdminStats {
    totalUsers: bigint;
    totalDonations: bigint;
    totalSmiles: bigint;
}
export interface UserProfile {
    id: Principal;
    bio?: string;
    profilePicUrl?: string;
    lastLoginTime: bigint;
    referralCode: string;
    country: string;
    name: string;
    badges: Array<Badge>;
    joinedAt: bigint;
    lastPostDate: bigint;
    referralCount: bigint;
    deactivatedAt?: bigint;
    email: string;
    referredBy?: string;
    tokens: bigint;
    unlockedStickers: Array<string>;
    isPublic: boolean;
    phone?: string;
    totalSmiles: bigint;
    location?: string;
    currentStreak: bigint;
}
export enum BadgeId {
    TOKENS_100 = "TOKENS_100",
    TOKENS_500 = "TOKENS_500",
    TOKENS_1000 = "TOKENS_1000",
    STREAK_30 = "STREAK_30",
    STREAK_3 = "STREAK_3",
    STREAK_7 = "STREAK_7"
}
export interface backendInterface {
    bulkDeleteSmiles(ids: Array<string>): Promise<Result_4>;
    buySticker(stickerId: string, cost: bigint): Promise<Result>;
    chatWithPookie(message: string, history: Array<ChatMessage>): Promise<Result_1>;
    deactivateAccount(): Promise<Result_1>;
    deleteAccount(): Promise<Result_1>;
    deleteSmile(smileId: string): Promise<Result_7>;
    getAdminStats(): Promise<AdminStats>;
    getAllUsers(): Promise<Array<UserSummary>>;
    getCookieConsent(): Promise<boolean>;
    getDonations(): Promise<Array<Donation>>;
    getLastLoginTime(): Promise<Result_6>;
    getMonthlyLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMySmiles(): Promise<Array<Smile>>;
    getNotifications(): Promise<Array<LikeNotification>>;
    getReferralCode(): Promise<Result_1>;
    getSmileAnalytics(smileId: string): Promise<Result_5>;
    getSmileByInvite(code: string): Promise<Result_3>;
    getSmiles(): Promise<Array<Smile>>;
    getTopDonors(): Promise<Array<TopDonor>>;
    getTrendingSmiles(): Promise<Array<Smile>>;
    getWeeklyLeaderboard(): Promise<Array<LeaderboardEntry>>;
    likeSmile(smileId: string): Promise<Result_4>;
    markAllNotificationsRead(): Promise<void>;
    postSmile(input: SmileInput): Promise<Result_3>;
    reactivateAccount(): Promise<Result_1>;
    recordDonation(donorName: string, amount: string, paymentMethod: string, message: string | null): Promise<Result_2>;
    recordReferral(code: string): Promise<Result_1>;
    recordSmileShare(smileId: string): Promise<void>;
    recordSmileView(smileId: string): Promise<void>;
    registerUser(input: RegisterInput): Promise<Result>;
    setCookieConsent(): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateLastLoginTime(): Promise<void>;
    updateProfile(input: UpdateProfileInput): Promise<Result>;
    updateProfilePicture(blobId: string, picUrl: string): Promise<Result>;
}
import type { Badge as _Badge, BadgeId as _BadgeId, Donation as _Donation, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Smile as _Smile, SmileInput as _SmileInput, UpdateProfileInput as _UpdateProfileInput, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async bulkDeleteSmiles(arg0: Array<string>): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeleteSmiles(arg0);
                return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeleteSmiles(arg0);
            return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async buySticker(arg0: string, arg1: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.buySticker(arg0, arg1);
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buySticker(arg0, arg1);
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async chatWithPookie(arg0: string, arg1: Array<ChatMessage>): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.chatWithPookie(arg0, arg1);
                return from_candid_Result_1_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chatWithPookie(arg0, arg1);
            return from_candid_Result_1_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateAccount(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateAccount();
                return from_candid_Result_1_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateAccount();
            return from_candid_Result_1_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAccount(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount();
                return from_candid_Result_1_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount();
            return from_candid_Result_1_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSmile(arg0: string): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSmile(arg0);
                return from_candid_Result_7_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSmile(arg0);
            return from_candid_Result_7_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCookieConsent(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getCookieConsent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCookieConsent();
            return result;
        }
    }
    async getDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonations();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonations();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastLoginTime(): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastLoginTime();
                return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastLoginTime();
            return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyLeaderboard();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySmiles(): Promise<Array<Smile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySmiles();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySmiles();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<LikeNotification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return result;
        }
    }
    async getReferralCode(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralCode();
                return from_candid_Result_1_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralCode();
            return from_candid_Result_1_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSmileAnalytics(arg0: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmileAnalytics(arg0);
                return from_candid_Result_5_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmileAnalytics(arg0);
            return from_candid_Result_5_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSmileByInvite(arg0: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmileByInvite(arg0);
                return from_candid_Result_3_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmileByInvite(arg0);
            return from_candid_Result_3_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSmiles(): Promise<Array<Smile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmiles();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmiles();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopDonors(): Promise<Array<TopDonor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopDonors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopDonors();
            return result;
        }
    }
    async getTrendingSmiles(): Promise<Array<Smile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingSmiles();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingSmiles();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyLeaderboard();
            return result;
        }
    }
    async likeSmile(arg0: string): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.likeSmile(arg0);
                return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeSmile(arg0);
            return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async postSmile(arg0: SmileInput): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.postSmile(to_candid_SmileInput_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_3_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postSmile(to_candid_SmileInput_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_3_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async reactivateAccount(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.reactivateAccount();
                return from_candid_Result_1_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactivateAccount();
            return from_candid_Result_1_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordDonation(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDonation(arg0, arg1, arg2, to_candid_opt_n33(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_2_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDonation(arg0, arg1, arg2, to_candid_opt_n33(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_2_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordReferral(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.recordReferral(arg0);
                return from_candid_Result_1_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordReferral(arg0);
            return from_candid_Result_1_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordSmileShare(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSmileShare(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSmileShare(arg0);
            return result;
        }
    }
    async recordSmileView(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSmileView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSmileView(arg0);
            return result;
        }
    }
    async registerUser(arg0: RegisterInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setCookieConsent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCookieConsent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCookieConsent();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateLastLoginTime(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastLoginTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastLoginTime();
            return result;
        }
    }
    async updateProfile(arg0: UpdateProfileInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_UpdateProfileInput_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_UpdateProfileInput_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfilePicture(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfilePicture(arg0, arg1);
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfilePicture(arg0, arg1);
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BadgeId_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BadgeId): BadgeId {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Badge_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Badge): Badge {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Donation_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donation): Donation {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Smile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Smile): Smile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BadgeId;
    icon: string;
    name: string;
    description: string;
    earnedAt: bigint;
}): {
    id: BadgeId;
    icon: string;
    name: string;
    description: string;
    earnedAt: bigint;
} {
    return {
        id: from_candid_BadgeId_n11(_uploadFile, _downloadFile, value.id),
        icon: value.icon,
        name: value.name,
        description: value.description,
        earnedAt: value.earnedAt
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    paymentMethod: string;
    createdAt: bigint;
    donorName: string;
    message: [] | [string];
    donorPrincipal: string;
    amount: string;
}): {
    id: string;
    paymentMethod: string;
    createdAt: bigint;
    donorName: string;
    message?: string;
    donorPrincipal: string;
    amount: string;
} {
    return {
        id: value.id,
        paymentMethod: value.paymentMethod,
        createdAt: value.createdAt,
        donorName: value.donorName,
        message: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.message)),
        donorPrincipal: value.donorPrincipal,
        amount: value.amount
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    profilePicUrl: [] | [string];
    userName: string;
    shares: bigint;
    userState: [] | [string];
    views: bigint;
    userId: Principal;
    createdAt: bigint;
    likedBy: Array<Principal>;
    likes: bigint;
    inviteCode: [] | [string];
    userCountry: string;
    userRegion: [] | [string];
    imageBlobId: string;
}): {
    id: string;
    profilePicUrl?: string;
    userName: string;
    shares: bigint;
    userState?: string;
    views: bigint;
    userId: Principal;
    createdAt: bigint;
    likedBy: Array<Principal>;
    likes: bigint;
    inviteCode?: string;
    userCountry: string;
    userRegion?: string;
    imageBlobId: string;
} {
    return {
        id: value.id,
        profilePicUrl: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.profilePicUrl)),
        userName: value.userName,
        shares: value.shares,
        userState: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.userState)),
        views: value.views,
        userId: value.userId,
        createdAt: value.createdAt,
        likedBy: value.likedBy,
        likes: value.likes,
        inviteCode: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.inviteCode)),
        userCountry: value.userCountry,
        userRegion: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.userRegion)),
        imageBlobId: value.imageBlobId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    bio: [] | [string];
    profilePicUrl: [] | [string];
    lastLoginTime: bigint;
    referralCode: string;
    country: string;
    name: string;
    badges: Array<_Badge>;
    joinedAt: bigint;
    lastPostDate: bigint;
    referralCount: bigint;
    deactivatedAt: [] | [bigint];
    email: string;
    referredBy: [] | [string];
    tokens: bigint;
    unlockedStickers: Array<string>;
    isPublic: boolean;
    phone: [] | [string];
    totalSmiles: bigint;
    location: [] | [string];
    currentStreak: bigint;
}): {
    id: Principal;
    bio?: string;
    profilePicUrl?: string;
    lastLoginTime: bigint;
    referralCode: string;
    country: string;
    name: string;
    badges: Array<Badge>;
    joinedAt: bigint;
    lastPostDate: bigint;
    referralCount: bigint;
    deactivatedAt?: bigint;
    email: string;
    referredBy?: string;
    tokens: bigint;
    unlockedStickers: Array<string>;
    isPublic: boolean;
    phone?: string;
    totalSmiles: bigint;
    location?: string;
    currentStreak: bigint;
} {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.bio)),
        profilePicUrl: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.profilePicUrl)),
        lastLoginTime: value.lastLoginTime,
        referralCode: value.referralCode,
        country: value.country,
        name: value.name,
        badges: from_candid_vec_n8(_uploadFile, _downloadFile, value.badges),
        joinedAt: value.joinedAt,
        lastPostDate: value.lastPostDate,
        referralCount: value.referralCount,
        deactivatedAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.deactivatedAt)),
        email: value.email,
        referredBy: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.referredBy)),
        tokens: value.tokens,
        unlockedStickers: value.unlockedStickers,
        isPublic: value.isPublic,
        phone: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.phone)),
        totalSmiles: value.totalSmiles,
        location: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.location)),
        currentStreak: value.currentStreak
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    TOKENS_100: null;
} | {
    TOKENS_500: null;
} | {
    TOKENS_1000: null;
} | {
    STREAK_30: null;
} | {
    STREAK_3: null;
} | {
    STREAK_7: null;
}): BadgeId {
    return "TOKENS_100" in value ? BadgeId.TOKENS_100 : "TOKENS_500" in value ? BadgeId.TOKENS_500 : "TOKENS_1000" in value ? BadgeId.TOKENS_1000 : "STREAK_30" in value ? BadgeId.STREAK_30 : "STREAK_3" in value ? BadgeId.STREAK_3 : "STREAK_7" in value ? BadgeId.STREAK_7 : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        shares: bigint;
        views: bigint;
        likes: bigint;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        shares: bigint;
        views: bigint;
        likes: bigint;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Smile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Smile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Smile_n25(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Donation;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Donation;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Donation_n19(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n5(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donation>): Array<Donation> {
    return value.map((x)=>from_candid_Donation_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Smile>): Array<Smile> {
    return value.map((x)=>from_candid_Smile_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Badge>): Array<Badge> {
    return value.map((x)=>from_candid_Badge_n9(_uploadFile, _downloadFile, x));
}
function to_candid_SmileInput_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SmileInput): _SmileInput {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileInput_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileInput): _UpdateProfileInput {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userState?: string;
    inviteCode?: string;
    userRegion?: string;
    imageBlobId: string;
}): {
    userState: [] | [string];
    inviteCode: [] | [string];
    userRegion: [] | [string];
    imageBlobId: string;
} {
    return {
        userState: value.userState ? candid_some(value.userState) : candid_none(),
        inviteCode: value.inviteCode ? candid_some(value.inviteCode) : candid_none(),
        userRegion: value.userRegion ? candid_some(value.userRegion) : candid_none(),
        imageBlobId: value.imageBlobId
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    name?: string;
    email?: string;
    isPublic?: boolean;
    phone?: string;
    location?: string;
}): {
    bio: [] | [string];
    name: [] | [string];
    email: [] | [string];
    isPublic: [] | [boolean];
    phone: [] | [string];
    location: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        isPublic: value.isPublic ? candid_some(value.isPublic) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
